In [1]:
import cvxpy as cp
import numpy as np

## Задание 1

#### Условия:
Для задачи линейного программирования минимизировать $$c^Tx$$ при условии $$Ax = b, x \ge 0$$


#### Решение:
$$L(x, \lambda, \mu) = c^T x - \lambda^T x + \mu^T Ax - \mu^T b$$
$$q(\lambda, \mu) = \inf L(x, \lambda, \mu) = \inf (c^T x - \lambda^T x + \mu^T Ax - \mu^T b)$$
Тогда так как $x \in R^n:$
$$q(\lambda, \mu) = \begin{cases}
-\mu^Tb      & c^T - \lambda^T + \mu^TA = 0  \\
-\infty      & c^T - \lambda^T + \mu^TA \neq 0
\end{cases}$$
Тогда двойственная задача: минимизировать $\mu^Tb$ при $c^T - \lambda^T + \mu^TA = 0, \mu \ge 0$

In [2]:
def solve1(A, b, c):
    m = cp.Variable(b.shape[0])
    l = cp.Variable(c.shape[0])
    cp.Problem(cp.Minimize(m.T @ b),[c.T - l.T + m.T @ A == 0, l >= 0]).solve()
    return l.value, m.value

A = np.array([[15, 4, 1, 0, 0], [11, 5, 0, 1, 0], [9, 10, 0, 0, 1]])
b = np.array([1095, 865, 1080])
c = np.array([-3, -2, 0, 0, 0])

l, mu = solve1(A, b, c)
l, mu

(array([-5.33529973e-10, -1.40225863e-09, -8.86079471e-10,  1.84615386e-01,
         1.07692307e-01]),
 array([-8.88152565e-10,  1.84615386e-01,  1.07692307e-01]))

Из того что $l_i$ не равны 0 можно заключить что $x_i = 0$, а остальные найдутся через $Ax = b$

In [3]:
def solve11(A, b, c, l, mu):
    z = np.isclose(l, 0)
    A_z = A[:, z]
    x_z = np.linalg.inv(A_z) @ b
    res = np.zeros(c.shape)
    res[z] = x_z
    return res

In [4]:
solve11(A, b, c, l, mu)

array([50., 63., 93.,  0.,  0.])

## Задание 2

In [5]:
def solve2(x):
    c = cp.Variable((1, x.shape[1]))
    problem = cp.Problem(cp.Minimize(cp.max(cp.sum((x - c) ** 2, axis=1))))
    problem.solve()
    return np.sqrt(problem.value), c.value

solve2(np.array([[1, 3],
                 [-2, 5],
                 [1, 8],
                 [3, -2],
                 [0, -11],
                 [-2, 2]]
               ))

(9.513148719192383, array([[ 0.49998904, -1.49999941]]))